# Generated by Django 3.1 on 2020-12-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_center_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vaccinated',
            new_name='alzheimer',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='allergy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bloodType',
            field=models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='covid_vacc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='stroke',
            field=models.BooleanField(default=False),
        ),
    ]
