# Generated by Django 3.1 on 2020-12-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_slot'),
        ('users', '0002_auto_20201202_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
