# Generated by Django 3.1 on 2020-12-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201204_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bloodType',
            field=models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type'), ('NA', 'Not Available')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
