# Generated by Django 3.1 on 2020-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201204_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_card',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
