# Generated by Django 3.1 on 2020-12-02 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0002_center_user'),
        ('users', '0002_auto_20201202_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('leaving_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('Waitlisted', 'Waitlist'), ('pending', 'Pending'), ('completed', 'Completed'), ('arrived', 'Arrived'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
