# Generated by Django 3.1 on 2020-12-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_slot'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='center',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='leaving_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.slot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('arrived', 'Arrived'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
