# Generated by Django 3.1 on 2020-08-30 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.UUIDField(default='53797018a7', editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Name of the Center', max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=20, message='Minimum Length of 20 ')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, default='project_header/default.png', null=True, upload_to='project_header')),
                ('header_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='project_logo')),
                ('published', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
            },
        ),
    ]
