# Generated by Django 3.1 on 2020-08-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='center',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='id',
            field=models.UUIDField(default='c1a775c504', editable=False, primary_key=True, serialize=False),
        ),
    ]
