name: test-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SECRET_KEY: foo
  SQL_ENGINE: django.db.backends.postgresql
  SQL_DATABASE: usap
  SQL_USER: usap
  SQL_PASSWORD: usap
  SQL_HOST: db
  SQL_PORT: 5432
jobs:
  backend_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker image
        run: docker-compose -f docker-compose-test.yml up -d